language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository

before_script:
    - chmod +x gradlew
#Build, and run tests
script: "./gradlew clean build"
sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  - GRADLE_OPTS="-XX:MaxPermSize=1024m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"