language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra
  - extra-google-m2repository
  - extra-android-m2repository

script:
  ./gradlew build